baseURL = "/"
languageCode = "en-us"
title = "Gardiner Car And Truck Wash"
theme = "blank"
googleAnalytics = "UA-137992203-1"

disableKinds = ["taxonomy", "taxonomyTerm"]

[menu]
    [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

    [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 2

    [[menu.main]]
    identifier = "about-us"
    name = "About Us"
    url = "/about-us/"
    weight = 3

    [[menu.main]]
    identifier = "location"
    name = "Location"
    url = "/location/"
    weight = 4

    [[menu.main]]
    identifier = "contact-us"
    name = "Contact Us"
    url = "/contact-us/"
    weight = 5
